/*
 * US_prg.c
 *
 *  Created on: Mar 2, 2023
 *      Author: ahmed
 */
#include "Error_State.h"
#include "STD_TYPES.h"
#include "avr/delay.h"
#include "Mcu_HW.h"
#include "DIO_Int.h"
#include "TIMER_int.h"
#include "TIMER1_int.h"
#include "US_priv.h"
#include "US_int.h"

extern Timer0_cfg_type timer0_cfg1;
u16 TIMER1_ICR_reading;
u8 edgeCount=0;

ES_t H_US_enu_init(){
	ES_t Local_enuErrorState= ES_OK;
	M_TIMER1_ICU_setCallBack(TIMER1_IC_int, H_US_enu__edgeProcessing,NULL);
	return Local_enuErrorState;
}
 void H_US_enu_send_trig(){
	M_DIO_void_setPinValue(DIO_PD1,DIO_HIGH);
	//M_TIMER_enum_Timer0_setDelayTimeMilliSec(timer0_cfg1, 1);
	_delay_us(1000);
	M_DIO_void_setPinValue(DIO_PD1, DIO_LOW);
}
ES_t H_US_enu_calculate_distance(f32 * copy_distance_ptr){
	ES_t Local_enuErrorState = ES_OK;
	H_US_enu_send_trig();
	_delay_us(5);
	*copy_distance_ptr = 0010625 *TIMER1_ICR_reading;
	H_LCD_void_sendIntNum(TIMER1_ICR_reading);
	return Local_enuErrorState;
}

ES_t H_US_enu__edgeProcessing(){
	ES_t Local_enuErrorState = ES_OK;
	edgeCount++;

	if (edgeCount == 1)
	{
		/* Clear the timer counter register to start measurements from the first detected rising edge */
		M_TIMER1_ICU_clearTimer();

		/* Detect falling edge at the Echo pin */
		M_TIMER1_enu_ICU_void_setTrigg(falling_edge);
	}
	else if(edgeCount == 2)
	{
		/* Store the high time (pulse time) generated by the ultrasonic sensor */
		M_TIMER1_enu_ICU_takeReading(&TIMER1_ICR_reading);

		/* Detect rising edge at the Echo pin */
		M_TIMER1_enu_ICU_void_setTrigg(rising_edge);

		/* Clear the timer counter register to start measurements again */
		M_TIMER1_ICU_clearTimer();

		edgeCount = 0;
	}
	else{
		Local_enuErrorState = ES_OUT_OF_RANGE;
	}
return Local_enuErrorState;
}
